"""
Base Agent for ERC-8004 Registry Interactions

This module provides the foundational class for agents that interact with
the ERC-8004 registry contracts.
"""

import json
import os
import socket
from typing import Dict, Optional, Any
from web3 import Web3
from web3.contract import Contract
from dotenv import load_dotenv

load_dotenv()

class ERC8004BaseAgent:
    """Base class for agents interacting with ERC-8004 registries"""

    def __init__(self, agent_domain: str, private_key: Optional[str] = None):
        """
        Initialize the base agent

        Args:
            agent_domain: The domain where this agent's AgentCard is hosted
            private_key: Private key for signing transactions (optional - generated by dstack if not provided)
        """
        self.agent_domain = agent_domain

        # Generate or use provided private key
        if private_key is None:
            self.private_key = self._generate_tee_key()
        else:
            self.private_key = private_key

        # Track if we're in TEE environment
        self.is_tee_environment = self._detect_tee_environment()

        # Initialize Web3 connection with robust error handling
        rpc_url = os.getenv('RPC_URL', 'http://127.0.0.1:8545')
        
        try:
            self.w3 = Web3(Web3.HTTPProvider(rpc_url))
            
            if not self.w3.is_connected():
                print(f"⚠️ Web3 connection failed to {rpc_url}, running in offline mode")
                # Create mock Web3 instance for offline functionality
                self.w3 = self._create_offline_web3()
                self.offline_mode = True
            else:
                # Test the connection
                try:
                    latest_block = self.w3.eth.get_block('latest')
                    chain_id = self.w3.eth.chain_id
                    
                    print(f"✅ Web3 connected to {rpc_url}")
                    print(f"   Chain ID: {chain_id}")
                    print(f"   Latest Block: {latest_block.number}")
                    self.offline_mode = False
                except Exception as e:
                    print(f"⚠️ Web3 connected but blockchain access failed: {e}")
                    print("   Running in limited connectivity mode")
                    self.offline_mode = True
            
        except Exception as e:
            print(f"⚠️ Web3 initialization failed: {e}")
            print("   Creating offline mode for agent functionality")
            self.w3 = self._create_offline_web3()
            self.offline_mode = True
        
        # Load account from private key
        from eth_account import Account
        # Clean and validate private key
        clean_private_key = private_key
        if clean_private_key.startswith('0x'):
            clean_private_key = clean_private_key[2:]
            
        # Validate hex format
        if not all(c in '0123456789abcdefABCDEF' for c in clean_private_key):
            raise ValueError(f"Private key contains invalid characters")
            
        if len(clean_private_key) != 64:
            raise ValueError(f"Private key wrong length: {len(clean_private_key)} (expected 64)")
            
        self.account = Account.from_key(clean_private_key)
        self.address = self.account.address
        
        # Load contract addresses from deployment
        self._load_contract_addresses()
        
        # Initialize contract instances
        self._init_contracts()
        
        # Agent registry info
        self.agent_id: Optional[int] = None
        self._check_registration()
    
    def _load_contract_addresses(self):
        """Load contract addresses from deployed_contracts.json or environment"""
        try:
            # Try environment variables first (for production)
            tee_verifier_addr = os.getenv('TEE_VERIFIER_ADDRESS')
            identity_addr = os.getenv('IDENTITY_REGISTRY_ADDRESS')
            reputation_addr = os.getenv('REPUTATION_REGISTRY_ADDRESS') 
            validation_addr = os.getenv('VALIDATION_REGISTRY_ADDRESS')
            
            if tee_verifier_addr and identity_addr and reputation_addr and validation_addr:
                print("📝 Using contract addresses from environment variables")
                self.tee_verifier_address = self.w3.to_checksum_address(tee_verifier_addr)
                self.identity_registry_address = self.w3.to_checksum_address(identity_addr)
                self.reputation_registry_address = self.w3.to_checksum_address(reputation_addr)
                self.validation_registry_address = self.w3.to_checksum_address(validation_addr)
                
                print(f"   TEE Verifier: {self.tee_verifier_address}")
                print(f"   Identity Registry: {self.identity_registry_address}")
                print(f"   Reputation Registry: {self.reputation_registry_address}")
                print(f"   Validation Registry: {self.validation_registry_address}")
                return
            
            # Fallback to deployed_contracts.json
            print("📝 Loading contract addresses from deployed_contracts.json...")
            with open('deployed_contracts.json', 'r') as f:
                deployment = json.load(f)
                contracts = deployment['contracts']
                
                # Ensure addresses are checksummed
                self.tee_verifier_address = self.w3.to_checksum_address(contracts['TEEVerifier'])
                self.identity_registry_address = self.w3.to_checksum_address(contracts['IdentityRegistry'])
                self.reputation_registry_address = self.w3.to_checksum_address(contracts['ReputationRegistry'])
                self.validation_registry_address = self.w3.to_checksum_address(contracts['ValidationRegistry'])
                
                print(f"   TEE Verifier: {self.tee_verifier_address}")
                print(f"   Identity Registry: {self.identity_registry_address}")
                print(f"   Reputation Registry: {self.reputation_registry_address}")
                print(f"   Validation Registry: {self.validation_registry_address}")
                
        except FileNotFoundError:
            # Last resort - use TEE-enhanced Base Sepolia addresses
            print("⚠️ No contract deployment found, using TEE-enhanced Base Sepolia fallback addresses")
            self.tee_verifier_address = "0x75e8FEb5820DC4d0E795F0517646212BBB4fB41A"
            self.identity_registry_address = "0x4bE957cceC6aEc4258F2419BcAF5B5341B14052f"
            self.reputation_registry_address = "0xCd42dF97D96CB4aB35f985F8133786386BBbFc5d"
            self.validation_registry_address = "0x4EB31a7bB1134872c980d6cfbd8A9DFF5b39f795"
            
        except Exception as e:
            raise Exception(f"Failed to load contract addresses: {e}")
    
    def _create_offline_web3(self):
        """Create offline Web3 instance for agent functionality without blockchain"""
        class OfflineWeb3:
            def __init__(self):
                self.eth = OfflineEth()
                
            def is_connected(self):
                return False
                
            def to_checksum_address(self, addr):
                return addr
                
        class OfflineEth:
            def __init__(self):
                self.chain_id = 84532  # Base Sepolia
                
        return OfflineWeb3()
    
    def _load_contract_abi(self, contract_name: str) -> list:
        """Load contract ABI from compiled artifacts"""
        abi_path = f"contracts/out/{contract_name}.sol/{contract_name}.json"
        
        with open(abi_path, 'r') as f:
            artifact = json.load(f)
            return artifact['abi']
    
    def _init_contracts(self):
        """Initialize contract instances (only when Web3 connection available)"""
        if self.offline_mode:
            print("⚠️ Offline mode: Contract instances not available")
            self.tee_verifier = None
            self.identity_registry = None
            self.reputation_registry = None
            self.validation_registry = None
            return
            
        try:
            # Load ABIs
            tee_verifier_abi = self._load_contract_abi('TEEVerifier')
            identity_abi = self._load_contract_abi('IdentityRegistry')
            reputation_abi = self._load_contract_abi('ReputationRegistry')
            validation_abi = self._load_contract_abi('ValidationRegistry')
            
            # Create contract instances
            self.tee_verifier = self.w3.eth.contract(
                address=self.tee_verifier_address,
                abi=tee_verifier_abi
            )
            
            self.identity_registry = self.w3.eth.contract(
                address=self.identity_registry_address,
                abi=identity_abi
            )
            
            self.reputation_registry = self.w3.eth.contract(
                address=self.reputation_registry_address,
                abi=reputation_abi
            )
            
            self.validation_registry = self.w3.eth.contract(
                address=self.validation_registry_address,
                abi=validation_abi
            )
            
            print("✅ All contract instances initialized successfully (including TEE Verifier)")
            
        except Exception as e:
            print(f"⚠️ Contract initialization failed: {e}")
            print("   Running without contract instances")
            self.tee_verifier = None
            self.identity_registry = None
            self.reputation_registry = None
            self.validation_registry = None
    
    async def register_agent(self, use_tee: bool = False, auto_register: bool = True) -> Optional[int]:
        """
        Register this agent on the blockchain

        Args:
            use_tee: Whether to use TEE-enhanced registration (requires TEE environment)
            auto_register: Whether to automatically register if not already registered

        Returns:
            Agent ID if registration successful, None otherwise
        """
        if self.offline_mode or not self.identity_registry:
            print("⚠️ Cannot register agent - offline mode or no contract")
            return None

        try:
            # Check if already registered
            try:
                result = self.identity_registry.functions.resolveByAddress(self.address).call()
                if result[0] > 0:  # AgentID > 0 means registered
                    self.agent_id = result[0]
                    print(f"✅ Agent already registered with ID: {self.agent_id}")
                    return self.agent_id
            except Exception as e:
                print(f"ℹ️  Agent not yet registered: {e}")

            # If not auto-register, just return None
            if not auto_register:
                print("ℹ️  Auto-registration disabled, agent not registered")
                return None

            print(f"🔐 Registering agent: {self.agent_domain}")

            # Check if we should use TEE registration
            should_use_tee = use_tee or self.is_tee_environment

            if should_use_tee and self.tee_verifier:
                print("   Using TEE-enhanced registration...")
                return await self._register_with_tee()
            else:
                print("   Using standard registration...")
                return self._register_standard()

        except Exception as e:
            print(f"❌ Agent registration failed: {e}")
            return None

    def _register_standard(self) -> Optional[int]:
        """Register agent using standard ERC-8004 registration"""
        try:
            # Check balance first
            balance = self.w3.eth.get_balance(self.address)
            registration_fee = self.identity_registry.functions.REGISTRATION_FEE().call()
            fee_in_eth = Web3.from_wei(registration_fee, 'ether')

            print(f"   Registration fee: {fee_in_eth} ETH")
            print(f"   Current balance: {Web3.from_wei(balance, 'ether')} ETH")

            if balance < registration_fee:
                print(f"❌ Insufficient funds for registration")
                print(f"   Required: {fee_in_eth} ETH")
                print(f"   Current: {Web3.from_wei(balance, 'ether')} ETH")
                print(f"   Please fund address: {self.address}")
                return None

            # Build transaction
            tx = self.identity_registry.functions.newAgent(
                self.agent_domain,
                self.address
            ).build_transaction({
                'from': self.address,
                'value': registration_fee,
                'gas': 200000,
                'gasPrice': self.w3.eth.gas_price,
                'nonce': self.w3.eth.get_transaction_count(self.address)
            })

            # Sign and send transaction
            signed_tx = self.account.sign_transaction(tx)
            tx_hash = self.w3.eth.send_raw_transaction(signed_tx.rawTransaction)
            print(f"   Transaction sent: {tx_hash.hex()}")

            # Wait for confirmation
            receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=60)

            if receipt.status == 1:
                # Extract agent ID from logs
                for log in receipt.logs:
                    try:
                        decoded_log = self.identity_registry.events.AgentRegistered().processLog(log)
                        agent_id = decoded_log['args']['agentId']
                        self.agent_id = agent_id
                        print(f"✅ Agent registered successfully with ID: {agent_id}")
                        return agent_id
                    except:
                        continue

            print("⚠️ Registration completed but could not extract agent ID")
            return None

        except Exception as e:
            print(f"❌ Standard registration failed: {e}")
            return None

    async def _register_with_tee(self) -> Optional[int]:
        """Register agent using TEE-enhanced registration"""
        try:
            # This would integrate with TEE agent service
            # For now, fall back to standard registration with TEE detection
            print("   TEE environment detected, using standard registration with TEE awareness")

            # Check if we can generate TEE attestation
            try:
                # Import TEE agent service functionality
                from agents.tee_agent_service import TEEAgentService

                # Generate TEE attestation
                tee_service = TEEAgentService(
                    agent_domain=self.agent_domain,
                    private_key=self.private_key
                )

                attestation = await tee_service.generate_tee_attestation()
                if attestation and attestation.verified:
                    print("   TEE attestation generated successfully")
                    # Use TEE-enhanced registration
                    return self._register_with_tee_attestation(attestation)
                else:
                    print("   TEE attestation generation failed, falling back to standard registration")
                    return self._register_standard()

            except ImportError:
                print("   TEE agent service not available, falling back to standard registration")
                return self._register_standard()

        except Exception as e:
            print(f"❌ TEE registration failed: {e}")
            return self._register_standard()  # Fallback to standard

    def _register_with_tee_attestation(self, attestation) -> Optional[int]:
        """Register agent with TEE attestation proof"""
        try:
            # Check balance first
            balance = self.w3.eth.get_balance(self.address)
            registration_fee = self.identity_registry.functions.REGISTRATION_FEE().call()

            if balance < registration_fee:
                print(f"❌ Insufficient funds for TEE registration")
                print(f"   Please fund address: {self.address}")
                return None

            # Use TEE-enhanced registration
            tx = self.identity_registry.functions.newAgentWithTEE(
                self.agent_domain,
                self.address,
                attestation.measurement_hash,
                attestation.quote_data
            ).build_transaction({
                'from': self.address,
                'value': registration_fee,
                'gas': 300000,  # Higher gas for TEE registration
                'gasPrice': self.w3.eth.gas_price,
                'nonce': self.w3.eth.get_transaction_count(self.address)
            })

            # Sign and send transaction
            signed_tx = self.account.sign_transaction(tx)
            tx_hash = self.w3.eth.send_raw_transaction(signed_tx.rawTransaction)
            print(f"   TEE Registration transaction sent: {tx_hash.hex()}")

            # Wait for confirmation
            receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=60)

            if receipt.status == 1:
                # Extract agent ID from logs
                for log in receipt.logs:
                    try:
                        decoded_log = self.identity_registry.events.AgentRegistered().processLog(log)
                        agent_id = decoded_log['args']['agentId']
                        self.agent_id = agent_id
                        print(f"✅ TEE Agent registered successfully with ID: {agent_id}")
                        return agent_id
                    except:
                        continue

            print("⚠️ TEE Registration completed but could not extract agent ID")
            return None

        except Exception as e:
            print(f"❌ TEE registration failed: {e}")
            return None
    
    def _check_registration(self):
        """Check if this agent is already registered and auto-register if needed"""
        if self.offline_mode or not self.identity_registry:
            print("⚠️ Offline mode: Cannot check registration, using demo agent ID")
            self.agent_id = 999  # Demo agent ID for offline mode
            return

        try:
            result = self.identity_registry.functions.resolveByAddress(self.address).call()
            if result[0] > 0:  # AgentID > 0 means registered
                self.agent_id = result[0]
                print(f"✅ Agent already registered with ID: {self.agent_id}")
            else:
                print("ℹ️  Agent not yet registered, attempting auto-registration...")
                # Auto-register if we're in TEE environment or registration is needed
                import asyncio
                asyncio.run(self.register_agent(auto_register=True))
        except Exception as e:
            print(f"ℹ️  Agent not yet registered: {e}")

    # Remove duplicate register_agent method - keeping the async version only
    def register_agent_sync(self) -> int:
        """
        Synchronous version of register_agent (legacy compatibility)

        Returns:
            Agent ID assigned by the registry
        """
        import asyncio
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            result = loop.run_until_complete(self.register_agent())
            return result if result else 999
        finally:
            loop.close()
    
    def authorize_feedback(self, client_agent_id: int) -> str:
        """
        Authorize a client agent to provide feedback to this server agent
        
        Args:
            client_agent_id: ID of the client agent to authorize
            
        Returns:
            Transaction hash
        """
        if not self.agent_id:
            raise ValueError("Agent must be registered first")
        
        print(f"🔐 Authorizing feedback from client agent {client_agent_id}")
        
        function = self.reputation_registry.functions.acceptFeedback(
            client_agent_id,
            self.agent_id
        )
        
        # Build and send transaction
        transaction = function.build_transaction({
            'from': self.address,
            'gas': 100000,
            'gasPrice': self.w3.eth.gas_price,
            'nonce': self.w3.eth.get_transaction_count(self.address),
        })
        
        try:
            signed_txn = self.w3.eth.account.sign_transaction(transaction, private_key=self.private_key)
            tx_hash = self.w3.eth.send_raw_transaction(signed_txn.raw_transaction)
            
            print(f"   Transaction hash: {tx_hash.hex()}")
            receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash)
            
            if receipt.status == 1:
                print(f"✅ Feedback authorization successful")
                return tx_hash.hex()
            else:
                print(f"❌ Transaction failed with status: {receipt.status}")
                raise Exception(f"Feedback authorization transaction failed with status {receipt.status}")
        except Exception as e:
            print(f"❌ Feedback authorization error: {str(e)}")
            raise Exception(f"Feedback authorization failed: {str(e)}")
    
    def request_validation(self, validator_agent_id: int, data_hash: bytes) -> str:
        """
        Request validation from a validator agent
        
        Args:
            validator_agent_id: ID of the validator agent
            data_hash: Hash of the data to be validated
            
        Returns:
            Transaction hash
        """
        if not self.agent_id:
            raise ValueError("Agent must be registered first")
        
        print(f"🔍 Requesting validation from agent {validator_agent_id}")
        
        function = self.validation_registry.functions.validationRequest(
            validator_agent_id,
            self.agent_id,
            data_hash
        )
        
        # Build and send transaction
        transaction = function.build_transaction({
            'from': self.address,
            'gas': 150000,
            'gasPrice': self.w3.eth.gas_price,
            'nonce': self.w3.eth.get_transaction_count(self.address),
        })
        
        signed_txn = self.w3.eth.account.sign_transaction(transaction, private_key=self.private_key)
        tx_hash = self.w3.eth.send_raw_transaction(signed_txn.raw_transaction)
        
        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash)
        
        if receipt.status == 1:
            print(f"✅ Validation request successful")
            return tx_hash.hex()
        else:
            raise Exception("Validation request failed")
    
    def submit_validation_response(self, data_hash: bytes, response: int) -> str:
        """
        Submit a validation response (for validator agents)
        
        Args:
            data_hash: Hash of the validated data
            response: Validation score (0-100)
            
        Returns:
            Transaction hash
        """
        if not self.agent_id:
            raise ValueError("Agent must be registered first")
        
        print(f"📊 Submitting validation response: {response}/100")
        
        function = self.validation_registry.functions.validationResponse(
            data_hash,
            response
        )
        
        # Build and send transaction
        transaction = function.build_transaction({
            'from': self.address,
            'gas': 120000,
            'gasPrice': self.w3.eth.gas_price,
            'nonce': self.w3.eth.get_transaction_count(self.address),
        })
        
        signed_txn = self.w3.eth.account.sign_transaction(transaction, private_key=self.private_key)
        tx_hash = self.w3.eth.send_raw_transaction(signed_txn.raw_transaction)
        
        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash)
        
        if receipt.status == 1:
            print(f"✅ Validation response submitted successfully")
            return tx_hash.hex()
        else:
            raise Exception("Validation response submission failed")
    
    def get_agent_info(self, agent_id: int) -> Dict[str, Any]:
        """Get information about an agent from the registry"""
        result = self.identity_registry.functions.getAgent(agent_id).call()
        return {
            'agent_id': result[0],
            'agent_domain': result[1],
            'agent_address': result[2]
        }

    def _generate_tee_key(self) -> str:
        """
        Generate private key using dstack getKey() in TEE environment
        Falls back to environment variable if not in TEE

        Returns:
            Private key as hex string (without 0x prefix)
        """
        if self.is_tee_environment:
            try:
                # Try to connect to dstack socket
                sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
                sock.settimeout(5.0)

                try:
                    sock.connect("/var/run/dstack.sock")
                    sock.send(b'getKey\n')
                    response = sock.recv(1024).decode().strip()

                    if response.startswith('0x'):
                        private_key = response[2:]
                    else:
                        private_key = response

                    # Validate the key
                    if len(private_key) == 64 and all(c in '0123456789abcdefABCDEF' for c in private_key):
                        print("✅ TEE private key generated successfully")
                        return private_key
                    else:
                        raise ValueError(f"Invalid private key format from dstack: {response}")

                except Exception as e:
                    print(f"⚠️ dstack socket connection failed: {e}")
                    # Fall back to legacy method
                    try:
                        sock.connect("/var/run/tappd.sock")
                        sock.send(b'getKey\n')
                        response = sock.recv(1024).decode().strip()

                        if response.startswith('0x'):
                            private_key = response[2:]
                        else:
                            private_key = response

                        if len(private_key) == 64 and all(c in '0123456789abcdefABCDEF' for c in private_key):
                            print("✅ Legacy TEE private key generated successfully")
                            return private_key
                        else:
                            raise ValueError(f"Invalid private key format from legacy TEE: {response}")

                    except Exception as legacy_e:
                        print(f"❌ All TEE key generation methods failed: {legacy_e}")
                        raise Exception("TEE key generation failed - are you in a TEE environment?")

            except Exception as e:
                print(f"❌ TEE key generation failed: {e}")
                raise Exception("TEE key generation failed - are you in a TEE environment?")
        else:
            # Fallback to environment variable for non-TEE environments
            private_key = os.getenv('PRIVATE_KEY')
            if not private_key:
                raise Exception(
                    "No private key provided and not in TEE environment. "
                    "Set PRIVATE_KEY environment variable or run in Phala TEE."
                )

            # Clean the private key
            if private_key.startswith('0x'):
                private_key = private_key[2:]

            return private_key

    def _detect_tee_environment(self) -> bool:
        """
        Detect if we're running in a TEE environment

        Returns:
            True if in TEE environment, False otherwise
        """
        # Check environment variables
        if os.getenv('TEE_MODE') == 'production':
            return True

        if os.getenv('PHALA_DEPLOYMENT') == 'true':
            return True

        # Check for dstack socket
        if os.path.exists('/var/run/dstack.sock'):
            return True

        # Check for legacy TEE socket
        if os.path.exists('/var/run/tappd.sock'):
            return True

        # Check if we're in a container with TEE simulation
        if os.getenv('TEE_SIMULATION_MODE') == 'true':
            return True

        return False

    def get_wallet_address(self) -> str:
        """
        Get the wallet address for this agent

        Returns:
            Wallet address as checksummed string
        """
        from eth_account import Account
        account = Account.from_key(self.private_key)
        return self.w3.to_checksum_address(account.address) 